Update entire Discovery Server documentation [9979]
eProsima/Discovery-Server-docs pull request #5
Opened 2020-11-18 11:00 UTC by rsanchez15

2021-06-11 10:31 UTC, richiware requested changes

2021-06-11 10:31 UTC, richiware commented on docs/user_manual/getting_started/getting_started.rst
> +For more information on the Discovery Server mechanism, please refer to the
Broken link

2021-06-11 10:31 UTC, richiware commented on docs/user_manual/usage/command_line.rst
> +        > . <path/to/discovery-server-ws>/discovery-server-ws/install/setup.bat
Use Windows slashes

2021-06-11 10:31 UTC, richiware commented on docs/xml_profiles/transports.rst
> +The XML basically mimics the `UDP attribute C++ source code <cpp_udp_settings>`_:
Broken link locally.

2021-06-11 10:31 UTC, richiware commented on docs/xml_profiles/transports.rst
> +The XML basically mimics the `TCP attribute C++ source code <cpp_tcp_settings>`_:
Broken link locally.

2021-06-15 14:27 UTC, rsanchez15 commented on .vscode/settings.json
> +    "restructuredtext.confPath": "${workspaceFolder}/docs"
No it shouldn't be there

2021-06-18 07:51 UTC, richiware requested changes

2021-06-18 07:51 UTC, richiware commented on docs/installation/installation_windows.rst
> +                --cmake-args -DTHIRDPARTY=ON -DLOG_LEVEL_INFO=ON \
```suggestion
                --cmake-args -DLOG_LEVEL_INFO=ON -DCOMPILE_EXAMPLES=ON \
```

2021-06-18 07:51 UTC, richiware commented on docs/installation/installation_windows.rst
> +                        -DCOMPILE_EXAMPLES=ON -DINTERNALDEBUG=ON -DCMAKE_BUILD_TYPE=Debug
```suggestion
                        -DINTERNALDEBUG=ON -DCMAKE_BUILD_TYPE=Debug
```

2021-06-18 07:51 UTC, richiware commented on docs/installation/installation_windows.rst
> +                --cmake-args -DTHIRDPARTY=ON -DCOMPILE_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release
```suggestion
                --cmake-args -DCOMPILE_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release
```

2021-06-18 07:51 UTC, richiware commented on docs/user_manual/usage/command_line.rst
> +    .. code-block:: bash
```suggestion
    .. code-block:: batch
```

2021-06-18 07:51 UTC, richiware commented on docs/xml_profiles/transports.rst
> +The XML basically mimics the `UDP attribute C++ source code <cpp_udp_settings>`_:
```suggestion
The XML basically mimics the :ref:`UDP attribute C++ source code <cpp_udp_settings>`:
```

2021-06-18 07:57 UTC, rsanchez15 commented on docs/installation/installation_windows.rst
> +                --cmake-args -DTHIRDPARTY=ON -DLOG_LEVEL_INFO=ON \
Compile examples would be duplicated

2021-06-18 07:58 UTC, rsanchez15 commented on docs/installation/installation_windows.rst
> +                        -DCOMPILE_EXAMPLES=ON -DINTERNALDEBUG=ON -DCMAKE_BUILD_TYPE=Debug
Okey this resolves the above duplicity

2021-06-18 08:10 UTC, richiware approved these changes

2021-06-18 08:11 UTC, merged